#!/usr/bin/env python3
"""Generate crates/pocshot-ui-slint/ui/icons.slint from lucide-slint.

Run:  python3 scripts/extract_lucide.py
The lucide-slint crate must be present in the cargo registry (e.g. after
`cargo info lucide-slint` or `cargo add lucide-slint --build` followed by
`cargo fetch`). Fails loudly if the crate or any icon is missing; never emits
a partial file.
"""
import glob
import os
import re
import sys

WANTED = [
    "MousePointer2", "Square", "Slash", "ArrowUpRight", "Circle", "Pen",
    "Highlighter", "EyeOff", "Hash", "Type", "Waves", "Grid3x3", "Eraser",
    "BoxSelect", "RotateCw", "Download", "Copy", "Undo2", "Redo2", "Pin",
    "ScanText", "Trash2", "Maximize", "Settings", "CircleHelp", "X",
    "Minus", "Plus", "Check",
]

ICONDISPLAY = '''export component IconDisplay inherits Rectangle {
    in property <Icon> icon;
    in-out property <length> size: 24px;
    in-out property <brush> stroke: #fff;
    in-out property <brush> stroke-fill: transparent;
    in-out property <float> stroke-width: 2.0;
    in-out property <bool> absolute-stroke-width: false;
    out property <length> calculated-stroke-width: absolute-stroke-width ? (stroke-width * 1px) : (size / 24 * stroke-width);

    width: size;
    height: size;
    clip: false;

    for path in icon.paths: Path {
        x: 0;
        y: 0;
        viewbox-x: path.viewbox-x;
        viewbox-y: path.viewbox-y;
        viewbox-width: path.viewbox-width;
        viewbox-height: path.viewbox-height;
        commands: path.command;
        stroke: parent.stroke;
        fill: path.has_fill ? parent.stroke : parent.stroke-fill;
        stroke-width: parent.calculated-stroke-width;
        stroke-line-cap: round;
        stroke-line-join: round;
    }
}
'''


def find_source():
    home = os.path.expanduser("~")
    pattern = os.path.join(home, ".cargo", "registry", "src", "*", "lucide-slint-*", "lucide.slint")
    matches = sorted(glob.glob(pattern))
    if not matches:
        sys.exit(f"lucide-slint not found under {pattern}; run `cargo info lucide-slint` first")
    return matches[-1]


def block(text, name):
    m = re.search(r"out property <Icon> " + re.escape(name) + r": \{(.*?)\n    \};", text, re.S)
    if not m:
        sys.exit(f"icon not found in lucide-slint: {name}")
    return m.group(1).strip("\n")


def main():
    src = find_source()
    text = open(src, encoding="utf-8").read()
    out = [
        "// Generated by scripts/extract_lucide.py from lucide-slint 1.48.0.",
        "// Lucide icons are ISC licensed; lucide-slint is MIT OR Apache-2.0.",
        "// Do not edit by hand: re-run the script to update.",
        "",
        "export struct PathElem {",
        "    viewbox-x: float,",
        "    viewbox-y: float,",
        "    viewbox-width: float,",
        "    viewbox-height: float,",
        "",
        "    command: string,",
        "    has_fill: bool,",
        "}",
        "",
        "export struct Icon {",
        "    paths: [PathElem],",
        "}",
        "",
        "export global Icons {",
    ]
    for name in WANTED:
        out.append(f"    out property <Icon> {name}: {{")
        out.append("    " + block(text, name))
        out.append("    };")
        out.append("")
    out += [
        "    // Custom filled variants. Lucide's Square/Circle have has_fill:false,",
        "    // so IconDisplay cannot fill them via stroke-fill.",
        "    out property <Icon> SquareFill: {",
        "        paths: [",
        "            { viewbox-x: 0, viewbox-y: 0, viewbox-width: 24, viewbox-height: 24,",
        '              command: "M 4 4 L 20 4 L 20 20 L 4 20 Z", has_fill: true },',
        "        ],",
        "    };",
        "",
        "    out property <Icon> CircleFill: {",
        "        paths: [",
        "            { viewbox-x: 0, viewbox-y: 0, viewbox-width: 24, viewbox-height: 24,",
        '              command: "M 12 3 C 7.02944 3 3 7.02944 3 12 C 3 16.9706 7.02944 21 12 21 C 16.9706 21 21 16.9706 21 12 C 21 7.02944 16.9706 3 12 3 Z", has_fill: true },',
        "        ],",
        "    };",
        "}",
        "",
        ICONDISPLAY,
    ]
    dest = os.path.join(os.path.dirname(__file__), "..", "crates", "pocshot-ui-slint", "ui", "icons.slint")
    dest = os.path.normpath(dest)
    result = "\n".join(out)
    assert "out property <Icon> SquareFill:" in result
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(result)
    print(f"wrote {dest}: {len(result)} bytes")


if __name__ == "__main__":
    main()
